/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#1b1c1c",
        "background": "#fcf9f8",
        "surface-container-high": "#eae7e7",
        "on-secondary-fixed-variant": "#474747",
        "secondary-fixed": "#e4e2e1",
        "surface-dim": "#dcd9d9",
        "on-error": "#ffffff",
        "on-surface-variant": "#584238",
        "on-primary-fixed": "#351000",
        "on-background": "#1b1c1c",
        "on-secondary-fixed": "#1b1c1c",
        "primary-container": "#9c3f00",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#fffbff",
        "on-tertiary-fixed-variant": "#474747",
        "secondary": "#5f5e5e",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "tertiary": "#5c5c5c",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#c8c6c6",
        "primary-fixed-dim": "#ffb693",
        "inverse-surface": "#303030",
        "surface-bright": "#fcf9f8",
        "primary": "#9c3f00",
        "inverse-on-surface": "#f3f0f0",
        "secondary-container": "#e4e2e1",
        "outline": "#8c7166",
        "surface-container": "#f0eded",
        "tertiary-container": "#757474",
        "on-tertiary-container": "#fefcfb",
        "tertiary-fixed": "#e4e2e2",
        "surface": "#fcf9f8",
        "inverse-primary": "#ffb693",
        "on-primary-fixed-variant": "#7a3000",
        "surface-container-low": "#f6f3f2",
        "primary-fixed": "#ffdbcc",
        "tertiary-fixed-dim": "#c8c6c6",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#656464",
        "surface-container-highest": "#e4e2e1",
        "surface-tint": "#a04100",
        "outline-variant": "#e0c0b2",
        "on-surface": "#1b1c1c",
        "surface-variant": "#e4e2e1"
      },
      borderRadius: {
        "none": "0px",
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Work Sans"],
        "label": ["Work Sans"]
      }
    },
  },
  plugins: [],
}
